change(freertos/smp/granular_locks): Updated prvYieldCore() coverage tests
FreeRTOS/FreeRTOS pull request #1292
Opened 2024-11-01 10:56 UTC by sudeep-mohanty

Description
-----------
This commit updates the code coverage tests for `prvYieldCore()`, viz., `test_coverage_prvYieldCore_core_id_ne_current_coreid` and `test_coverage_prvYieldCore_runstate_eq_yielding` by adding a unit test configuration to force preemption disable for the task invoking the coverage test.

This change is done to fix the CI test failures observed in the FreeRTOS-Kernel [PR#1154](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1154). The failure observed the GitHub action [here](https://github.com/sudeep-mohanty/FreeRTOS-Kernel/actions/runs/11612132105/job/32334942902) is necessary because the granular locks PR updates `xPreemptionDisable` to be nested. Reference [here](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1154/commits/e223842bf4292a9e33c68c396f4d5668e5cc95eb).

The change would not affect the current kernel without the granular changes as `xPreemptionDisable` is overwritted in the `vTaskPreemptionEnable()` call.

Test Steps
-----------
- FreeRTOS CI runs for the [PR#1154](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1154).

Checklist:
----------
- [x] I have tested my changes. No regression in existing tests.
- [x] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------
- #905 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-11-02 03:07 UTC, ActoryOu commented
Hi @sudeep-mohanty,
Thanks for your contribution! I'll reach out my colleague to review this.
Does this PR have dependency with #1154?

Thank you.

2024-11-02 08:27 UTC, sudeep-mohanty commented
Thanks @ActoryOu. This PR is a prerequisite for #1154

2024-11-07 22:56 UTC, jasonpcarroll reviewed
Looks good to me - but I find it worrying that we aren't initializing the entirety of the TCB to a known value, leading to undefined behavior like this... Could you additionally initialize the task TCBs to {0} ?

2024-11-08 07:21 UTC, sudeep-mohanty commented
Thanks for the review, @jasonpcarroll. I have updated it as you suggested.

2024-11-08 19:16 UTC, jasonpcarroll approved these changes

2024-11-08 19:22 UTC, jasonpcarroll requested changes
Fix the formatting. You can simply comment /bot run formatting on this PR to do that or you can use the git patch attached to the formatting workflow.

2024-11-11 08:54 UTC, sudeep-mohanty commented
Thanks for the review, @jasonpcarroll. I've updated the PR with the formatting changes necessary. Thanks.

2024-11-12 21:47 UTC, jasonpcarroll commented
Seems other tests have broken now ... but looking into it seems that you just need to merge main into your code as there were other UT changes due to a change to the kernel. Seeing as those are the only tests failing and those tests have already been fixed in another PR, I will approve.

2024-11-12 21:47 UTC, jasonpcarroll approved these changes

2024-11-15 23:58 UTC, jasonpcarroll requested changes
Honestly not sure why the unit tests are not passing after you merged main... could you look into why that is and correct it?

2024-12-06 17:33 UTC, jasonpcarroll commented
Any updates here?

2024-12-09 05:48 UTC, sudeep-mohanty commented
Hi @jasonpcarroll, Thanks for poking me on this. The work on the original PR which requires this change (https://github.com/FreeRTOS/FreeRTOS/pull/1295) has been on my back burner for a bit and hence I haven't looked in to the failure since then. Although, I did not really understand either why the kernel unit tests failed with this seemingly unrelated change. Nevertheless, I will take a look as soon as I have some time.

2024-12-18 09:10 UTC, closed without merging