Fix spellings
FreeRTOS/FreeRTOS pull request #302
Opened 2020-09-26 00:23 UTC by AniruddhaKanhere

Description
-----------
This PR adds multiple spelling corrections in files related to the TCP source code.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-09-26 00:33 UTC, divekarshubham commented on FreeRTOS-Plus/Test/CBMC/proofs/CBMCStubLibrary/tasksStubs.c
> +/* This function is another method apart from over-writting the defines to init the max
should be overwriting

2020-09-26 00:33 UTC, divekarshubham requested changes
Just one spell change

2020-09-26 00:42 UTC, AniruddhaKanhere commented
> Just one spell change

Thanks a lot Shubham! Nice catch.

2020-09-26 00:43 UTC, divekarshubham approved these changes

2020-09-28 16:53 UTC, gkwicker approved these changes

2020-09-28 16:53 UTC, gkwicker commented on FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/FreeRTOS_DHCP.c
> +		/* There was a problem with the randomizer. */
This is changing from English to American spelling – our dictionary is probably using American spelling.

2020-09-28 16:53 UTC, gkwicker commented on FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/FreeRTOS_TCP_IP.c
> +		/* Count the number of times it could not find the ARP address. */
This was fine before – the spell checker is not perfect and can't handle contractions.  You will see things like _wouldn_, _shouldn_, etc. in the lexicon.txt.

2020-09-28 16:55 UTC, merged