FreeRTOS+TCP Zynq: check frame type before calculating ICMP checksum (v3)
FreeRTOS/FreeRTOS pull request #304
Opened 2020-09-28 17:28 UTC by htibosch

Description
-----------
This PR will replace the earlier #177, of which the branch got lost.

The only significant change is in the function `xNetworkInterfaceOutput()`, in which the frame-type is checked before checking the protocol type.

I the current driver, outgoing ARP frames get a size warning. It doesn't cause incorrect behaviour, except for the size warnings in the logging.

Test Steps
-----------
Define `ipconfigDRIVER_INCLUDED_TX_IP_CHECKSUM` as `1` and send an outgoing ping. The ARP before the PING may not trigger a size warning, and the ICMP checksum shall be calculated correctly.

Related Issue
-----------
None.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-09-28 18:51 UTC, AniruddhaKanhere submitted a review, later dismissed

2020-09-28 19:57 UTC, AniruddhaKanhere commented
/bot run checks

2020-09-28 22:32 UTC, gkwicker requested changes
Fix stack size comment

2020-09-28 22:32 UTC, gkwicker commented on FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/Zynq/NetworkInterface.c
>  /* Default the size of the stack used by the EMAC deferred handler task to twice
This comment no longer matches the constant at line 87.

2020-09-29 15:51 UTC, AniruddhaKanhere approved these changes

2020-09-29 15:51 UTC, AniruddhaKanhere commented
/bot run checks

2020-09-29 15:51 UTC, AniruddhaKanhere commented
/bot run checks

2020-10-14 15:24 UTC, htibosch commented
This PR has moved to FreeRTOS-Plus-TCP [PR #19](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/19).

2020-10-14 15:24 UTC, closed without merging