Blinky Demo for Cortex M3 MPS2 on Qemu
FreeRTOS/FreeRTOS pull request #345
Opened 2020-10-14 04:52 UTC by alfred2g

Blinky Demo for Cortex M3 MPS2 on Qemu

Description
-----------
Implement the Blinky demo that runs on qemu for an emulated Cortex M3 MPS2 board

Test Steps
-----------
Ran Manually on Quemu:
```
parallels@parallels-Parallels-Virtual-Platform:~$ qemu-system-arm -machine mps2-an385  -monitor null -semihosting --semihosting-config enable=on,target=native -kernel /media/psf/Home/mps2_demo  -serial stdio -nographic
blinking
blinking
blinking
blinking
blinking
blinking
blinking
blinking
qemu-system-arm: terminating on signal 2
parallels@parallels-Parallels-Virtual-Platform:~$ 
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-19 07:33 UTC, cobusve commented on FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC/Readme.md
> +3. qemu-arm-system downlaod [here](https://www.qemu.org/download)
Spelling - tsk tsk ...

2020-10-19 07:34 UTC, cobusve commented on FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC/Readme.md
> +This Demo implemets the blinky demo, the user should expect the word
Spelling

2020-10-19 07:34 UTC, cobusve commented on FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC/Readme.md
> +"blinking" to be repeatedly prited on the screen
spelling

2020-10-19 07:35 UTC, cobusve commented on FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC/main_blinky.c
> +#define	mainQUEUE_SEND_TASK_PRIORITY		( tskIDLE_PRIORITY + 1 )
indentation

2020-10-19 07:36 UTC, cobusve commented on FreeRTOS/Demo/CORTEX_M3_MPS2_QEMU_GCC/main_blinky.c
> +            vTaskDelay(1000);
indentation

2020-10-19 07:36 UTC, cobusve requested changes
I marked some spelling and style problems

2020-10-20 17:32 UTC, cobusve approved these changes

2020-10-20 18:24 UTC, n9wxu approved these changes

2020-10-22 01:00 UTC, merged