Update pkcs11 submodule
FreeRTOS/FreeRTOS pull request #443
Opened 2020-12-04 18:45 UTC by alfred2g

Update pkcs11 submodule

Description
-----------
update pksc11 submodule head

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-04 18:48 UTC, lundinc2 approved these changes

2020-12-04 19:02 UTC, n9wxu approved these changes

2020-12-04 19:15 UTC, alfred2g commented
/but run checks

2020-12-08 18:32 UTC, lundinc2 requested changes
This can be closed, i have updated the sub module in a separate PR

2020-12-10 16:36 UTC, closed without merging