Update Readme.md
FreeRTOS/FreeRTOS pull request #939
Opened 2023-03-01 18:03 UTC by kar-rahul-aws

Update the documentation for Readme of the FreeRTOS_PLUS_TCP_ECHO_QEMU_msp2

Description
-----------
The documentation for the ReadMe for the QEMU demo is updated , with focus on giving a clear understanding to the user of :

1. The various address need to be set as part of configuration
2. The systems needed to run the Demo on (https://forums.freertos.org/t/example-freertos-tcp-echo-qemu-is-not-providing-the-desirable-result/)
3. A pictorial representation on how the QEMU setup functions after the Virtual Bridge is setup.

Test Steps
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-01 18:53 UTC, alfred2g commented on FreeRTOS-Plus/Demo/FreeRTOS_Plus_TCP_Echo_Qemu_mps2/Readme.md
> +2. Setting up MAC and IP Address
Could we specify which definitions would hold each? we always get questions from confused customers that map concepts to actual macros they need to fill up

2023-03-01 19:39 UTC, alfred2g approved these changes

2023-03-03 00:11 UTC, AniruddhaKanhere approved these changes

2023-03-06 09:32 UTC, ActoryOu requested changes

2023-03-09 06:49 UTC, aggarg approved these changes

2023-03-09 09:34 UTC, ActoryOu approved these changes

2023-03-09 09:41 UTC, merged