Added Posix Demo run in github action
FreeRTOS/FreeRTOS pull request #997
Opened 2023-04-21 01:17 UTC by xuelix

Description
-----------
During the action, after demo build, Posix_GCC port will run both Full demo and Blinky demo.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-22 05:39 UTC, n9wxu approved these changes

2023-04-22 06:28 UTC, n9wxu submitted a review, later dismissed

2023-04-24 17:58 UTC, jasonpcarroll commented on .github/workflows/freertos_demos.yml
> +          timeout 3m build/posix_demo | tee output.txt
One thing to be aware of with this to is that any command run in the action's- "run" field will fail the action if the exit status is not 0 ... which is a bit of an annoying caveat ...

2023-05-03 21:42 UTC, jasonpcarroll approved these changes

2023-05-03 21:54 UTC, jasonpcarroll requested changes

2023-05-03 21:54 UTC, jasonpcarroll commented on .github/workflows/freertos_demos.yml
> +        id: build-posix-gcc-demo
Rename this id to build-posix-gcc-full-demo

2023-05-03 21:54 UTC, jasonpcarroll commented on .github/workflows/freertos_demos.yml
> +        id: build-posix-gcc-demo
```suggestion
        id: build-posix-gcc-full-demo
```

2023-05-03 21:54 UTC, jasonpcarroll commented on .github/workflows/freertos_demos.yml
> +        if: success()
```suggestion
        if: success() || failure() && steps.build-posix-gcc-full-demo.outcome == 'success'
```

2023-05-03 21:54 UTC, jasonpcarroll commented on .github/workflows/freertos_demos.yml
> +        if: success() || failure() && steps.build-posix-gcc-demo.outcome == 'success'
```suggestion
        id: build-posix-gcc-blinky-demo
        if: success() || failure()
```

2023-05-03 21:54 UTC, jasonpcarroll commented on .github/workflows/freertos_demos.yml
> +        if: success() || failure() && steps.build-posix-gcc-demo.outcome == 'success'
```suggestion
        if: success() || failure() && steps.build-posix-gcc-blinky-demo.outcome == 'success'
```

2023-05-03 21:54 UTC, jasonpcarroll commented on .github/workflows/freertos_demos.yml
> +        if: success() || failure() && steps.build-posix-gcc-demo.outcome == 'success'
adding this id will allow you to differentiate between the two make steps. success() || failure() will make this run despite previous steps failing, but will still allow you to cancel the flow. You could add an ID to the install gcc step and add it as a dependency as well but probably not needed

2023-05-03 21:54 UTC, jasonpcarroll commented on .github/workflows/freertos_demos.yml
> +        if: success() || failure() && steps.build-posix-gcc-demo.outcome == 'success'
This will make it so this only runs as long as the build for the blinky demo succeeds if you commit my previous suggestion.

2023-05-03 21:54 UTC, jasonpcarroll commented on .github/workflows/freertos_demos.yml
> +        id: build-posix-gcc-demo
Rename this to this so you can differentiate between the two build steps

2023-05-03 22:42 UTC, jasonpcarroll approved these changes

2023-05-08 22:25 UTC, n9wxu approved these changes

2023-05-08 22:29 UTC, merged